apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace}}
  name: {{ .Values.serviceName}}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.servicePort}}
    protocol: TCP
    targetPort: {{ .Values.containerPort}}
  selector:
    app: {{ .Values.appName}}
